### ISSUE TITLE
Conflict Between WebRTC Audio and Mapbox Navigation Audio Playback

### ISSUE THREAD

**Issue by ProgrammerFaraz** [mapbox/mapbox-speech-swift#62]
I'm facing an issue while integrating WebRTC audio streaming and Mapbox Navigation audio in the same iOS application. When the Mapbox Navigation SDK plays audio (e.g., turn-by-turn instructions), it interrupts and stops the volume and mic of the ongoing WebRTC audio stream that uses AVAudioSession. This behavior negatively impacts the user experience, especially in scenarios where continuous communication via WebRTC is crucial alongside navigation.

### Steps to Reproduce
- Integrate WebRTC audio streaming using WebRTC's RTCAudioSession.
- Add Mapbox Navigation SDK to the project.
- Start a WebRTC audio stream.
- Trigger a navigation session that plays audio instructions (e.g., "Turn left in 100 meters").

### Expected Behavior
Mapbox Navigation audio should coexist with WebRTC audio:

- Both audio streams should play simultaneously without interruption.
- Navigation audio should not interfere with WebRTC audio streams.

### Actual Behavior
- Mapbox Navigation audio interrupts and stops the volume and mic of the WebRTC audio stream.
- After navigation audio finishes, WebRTC audio does not fully recover and it stops entirely.

### Technical Details
- **WebRTC Audio Configuration:** WebRTC uses RTCAudioSession.sharedInstance(), which internally relies on AVAudioSession configured with the .playAndRecord category and .voiceChat mode.
- **Mapbox Navigation Audio Configuration:** It appears that Mapbox uses AVAudioSession with the .playback category.
- **Conflict:** When Mapbox changes the AVAudioSession configuration for playback, it disrupts the WebRTC audio session.

**Comment by 1ec5** [comment]
This package only uses AVFoundation on the command line; the iOS version only vends at most the audio data for the client to play. You’ll probably want to report this issue in the mapbox-navigation-ios repository instead.
